### PR TITLE
Feature BL-15040 code linting

### PR DESCRIPTION
**Pull request by waringr**
## Description

Add phpcs and phpstan style checking and run them in the pre-commit hook

Related issue: https://dvsa.atlassian.net/browse/BL-15040

## Before submitting (or marking as "ready for review")

- [x] Does the pull request title follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification?
- [x] Have you performed a self-review of the code?
- [ ] Have you have added tests that prove the fix or feature is effective and working?
- [ ] Did you make sure to update any documentation relating to this change?

### CODE REVIEW

**Review by UndermountainK — COMMENTED** [review]
Looks good. I wonder if the class name change of exceptions will affect MTS.
Also i think we need github workflow update for phpstan

**Comment by waringr** [comment]
I _think_ phpstan is being run by the CI, at least it's in the workflow. Why there isn't a build for this repo though, I'm not sure.

**Comment by waringr** [comment]
And those error classes aren't being used anywhere in MOT or related repos according to the GH search.

**Review by PapaZouk — APPROVED** [review]

**Comment by UndermountainK** [comment]
> I _think_ phpstan is being run by the CI, at least it's in the workflow. Why there isn't a build for this repo though, I'm not sure.

I think currently workflow is disabled. Better to leave it that way cause psalm will fail and block this from merging

**Review by UndermountainK — APPROVED** [review]

**Pull request merged**
